import ProductList from "@/components/molecules/ProductList";
import { API_ROUTES } from "@/helpers/constants";
import heroImage from "@/images/heroImage.jpg";
import fetcher from "@/service/service";
import {
  selectSelectedProductId,
  setSelectedProductId,
} from "@/store/productSlice";
import { Product } from "@/types/types";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";

export async function getStaticProps() {
  console.log(process.env.NEXT_PUBLIC_SERVER_BASE_URL);
  const { data } = await fetcher(API_ROUTES.products);
  return {
    props: {
      productList: data,
    }, // will be passed to the page component as props
  };
}

export default function Home({ productList }: { productList: Product[] }) {
  const router = useRouter();
  const dispatch = useDispatch();
  const selectedProductId = useSelector(selectSelectedProductId);

  function handleProductItemClick(id: number) {
    dispatch(setSelectedProductId(id));
    router.replace(`products/${id}`);
  }

  return (
    <>
      <Head>
        <title>Key Combo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex justify-start h-[calc(100vh_-_58px)]"}>
        <div
          className={"h-full max-w-[375px] h-[2000px] w-full overflow-y-scroll"}
        >
          <ProductList
            selectedProductId={selectedProductId}
            products={productList}
            onClick={handleProductItemClick}
          />
        </div>
        <div className={"w-full h-full overflow-hidden"}>
          <div className={"flex justify-center"}>
            <Image src={heroImage} width={600} alt={"Lookup"} />
          </div>
        </div>
      </div>
    </>
  );
}
