import ProductCardList from "@/components/molecules/ProductCardList";
import { API_ROUTES } from "@/helpers/constants";
import fetcher from "@/service/service";
import {
  selectSelectedProductId,
  setSelectedProductId,
} from "@/store/productSlice";
import { Product } from "@/types/types";
import Head from "next/head";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";

export async function getStaticProps() {
  const { data } = await fetcher(API_ROUTES.products+'?populate[0]=logo');
  return {
    props: {
      productList: data,
    }, // will be passed to the page component as props
  };
}

export default function Home({ productList }: { productList: Product[] }) {
  const router = useRouter();
  const dispatch = useDispatch();
  const selectedProductId = useSelector(selectSelectedProductId);

  function handleProductItemClick(id: number) {
    dispatch(setSelectedProductId(id));
    router.replace(`products/${id}`);
  }

  return (
    <>
      <Head>
        <title>Key Combo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex justify-start sm:h-[calc(100vh_-_58px)] h-[calc(100vh_-_150px)] overflow-y-auto"}>
          <ProductCardList
            selectedProductId={selectedProductId}
            products={productList}
            onClick={handleProductItemClick}
          />
      </div>
    </>
  );
}
